BASE_IMAGE = ENV['BASE_IMAGE'] || 'srv6-calico-vpp-base'
CLUSTER_NAME = ENV['CLUSTER_NAME'] || 'srv6-calico-vpp-tests'
DATA_IF_MTU = '1380'
POD_NW_CIDR = ENV['POD_NW_CIDR'] || '172.16.0.0/16'
SERVICE_CIDR = ENV['SERVICE_CIDR'] || '10.96.0.0/12'
KUBETOKEN = ENV['KUBETOKEN'] || 'xvyy6d.6iw5i2ivk55xsklv'
KUBERNETES_VERSION = ENV['KUBERNETES_VERSION'] || '1.22.1'
NODE_NODESET = ''
NODE_NIC_PASSTHROUGH = ''
NODE = ENV['NODE'].to_i || 1
NODE_CPUS = ENV['NODE_CPUS'].to_i || 2
NODE_MEMORY_SIZE_GB = ENV['NODE_MEMORY_SIZE_GB'].to_i || 4
DISK_SIZE_GB = ENV['DISK_SIZE_GB'].to_i || 80
NODE_IP = ENV['NODE_IP'] || '192.168.11.254'
NODE_IP6 = ENV['NODE_IP6'] || 'fd11::1000'
NODE_IP6_GW = ENV['NODE_IP6_GW'] || 'fd11::1020'
NODE_IP4_GW = ENV['NODE_IP4_GW'] || '192.168.11.3'
NODE_IP4_NET = ENV['NODE_IP4_NET'] || '192.168.11.0/24'
WORKER_NODE_NAME = "worker#{NODE}"

Vagrant.configure('2') do |config|
    config.vm.box = BASE_IMAGE
    config.vm.box_check_update = false

    config.vm.boot_timeout = 900

    config.vm.provider :libvirt do |l|
        l.default_prefix = CLUSTER_NAME + '_'
        l.cpus = NODE_CPUS
        l.cputopology :sockets => '1', :cores => NODE_CPUS, :threads => '1'
        l.memory = NODE_MEMORY_SIZE_GB * 1024
        l.machine_virtual_size = DISK_SIZE_GB

        if NODE_NIC_PASSTHROUGH != ''
            l.pci parse_pci NODE_NIC_PASSTHROUGH
        end
        if NODE_NODESET != ''
            l.nodeset = NODE_NODESET
        end
    end

    config.vm.define "#{WORKER_NODE_NAME}" do |subconfig|
        subconfig.vm.hostname = "#{WORKER_NODE_NAME}"
        if NODE_NIC_PASSTHROUGH == ''
            subconfig.vm.network :private_network,
                :ip => NODE_IP,
                :libvirt__guest_ipv6 => "yes",
                :libvirt__ipv6_address => NODE_IP6,
                :libvirt__ipv6_prefix => "64"
        end
        
        # Provision
        subconfig.vm.provision "shell" do |s|
            s.path = "../vagrant/scripts/linux/prepare.sh"
            s.args = ["#{DATA_IF_MTU}", "#{NODE_IP}" , "#{NODE_IP6}", "#{NODE_IP6_GW}", "#{NODE_IP4_GW}", "#{NODE_IP4_NET}"]
        end

    end
end
