BASE_IMAGE = 'srv6-calico-vpp-base'
CLUSTER_NAME = 'srv6-calico-vpp-tests'
MASTER_CPUS = 2
MASTER_MEMORY_SIZE_GB = 4
DISK_SIZE_GB = 80
MASTER_NODESET = ''
MASTER_NIC_PASSTHROUGH = ''
MASTER_IP = '192.168.10.254'
MASTER_IP6 = 'fd10::1000'
NODE_IP6_GW = 'fd10::1020'
DATA_IF_MTU = '1380'
POD_NW_CIDR = '172.16.0.0/16'
SERVICE_CIDR = '10.96.0.0/12'
KUBETOKEN = 'xvyy6d.6iw5i2ivk55xsklv'
KUBERNETES_VERSION = '1.22.1'


Vagrant.configure('2') do |config|
    config.vm.box = BASE_IMAGE
    config.vm.box_check_update = false

    config.vm.boot_timeout = 900

    config.vm.provider :libvirt do |l|
        l.default_prefix = CLUSTER_NAME + '_'
        l.cpus = MASTER_CPUS
        l.cputopology :sockets => '1', :cores => MASTER_CPUS, :threads => '1'
        l.memory = MASTER_MEMORY_SIZE_GB * 1024
        l.machine_virtual_size = DISK_SIZE_GB

        if MASTER_NIC_PASSTHROUGH != ''
            l.pci parse_pci MASTER_NIC_PASSTHROUGH
        end
        if MASTER_NODESET != ''
            l.nodeset = MASTER_NODESET
        end
    end

    config.vm.define 'master' do |subconfig|
        subconfig.vm.hostname = 'master'
        if MASTER_NIC_PASSTHROUGH == ''
            subconfig.vm.network :private_network,
                :ip => MASTER_IP,
                :libvirt__guest_ipv6 => "yes",
                :libvirt__ipv6_address => MASTER_IP6,
                :libvirt__ipv6_prefix => "64"
        end
        # Provision
        subconfig.vm.provision :file do |provision|
            provision.source = 'docker/image_agent_srv6'
            provision.destination = '/tmp/image_agent_srv6'
        end
        subconfig.vm.provision :file do |provision|
            provision.source = 'docker/image_vpp_srv6'
            provision.destination = '/tmp/image_vpp_srv6'
        end
        subconfig.vm.provision "shell" do |s|
            s.path = "vagrant/scripts/linux/prepare.sh"
            s.args = ["#{DATA_IF_MTU}", "#{MASTER_IP}" , "#{MASTER_IP6}", "#{NODE_IP6_GW}"]
        end
        subconfig.vm.provision "shell" do |s|
            s.path = "vagrant/scripts/linux/master-k8s-init.sh"
            s.args = ["#{KUBERNETES_VERSION}", "#{MASTER_IP}" , "#{MASTER_IP6}", "#{POD_NW_CIDR}", "#{SERVICE_CIDR}" ,"#{KUBETOKEN}"]
        end

    end
end
