apiVersion: crd.projectcalico.org/v1 
kind: BGPPeer
metadata:
  name: my-peer-v4
spec:
  peerIP: 192.169.9.254
  asNumber: 64512
---
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: my-peer-v6
spec:
  peerIP: fd00:0:34::2
  asNumber: 64512