apiVersion: v1
kind: ConfigMap
metadata:
  name: srv6-config
  namespace: calico-vpp-dataplane
data:
  master: |
    --- 
    localsids: 
      DT4: "fcdd::aa:34b8:247c:36da:db44"
      DT6: "fcdd::aa:34b8:247c:36da:db45"
    node: master
    policies: 
  worker1: |
    --- 
    localsids: 
      DT4: "fcdd::11aa:c11:b42f:f17e:a682"
      DT6: "fcdd::11aa:c11:b42f:f17e:a683"
    node: worker1
    policies: 
  worker2: |
    --- 
    localsids: 
      DT4: "fcdd::12aa:d460:b250:45:b04"
      DT6: "fcdd::12aa:d460:b250:45:b05"
    node: worker2
