apiVersion: apps/v1

kind: DaemonSet

metadata:
  name: vpp-test-busybox
spec:
  selector:
    matchLabels:
      name: vpp-test-busybox
  template:
    metadata:
      labels:
        name: vpp-test-busybox
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: vpp-test-busybox
          image: busybox
          command: ["sleep"]
          args: ["2d"]
  
